use super::config::{ResolvedPocketBase, ResolvedService, ResolvedServiceKind, ServiceMap};
use anyhow::{Context, Result};
use std::cmp::Ordering;
use std::collections::BTreeMap;
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RenderedArtifacts {
    pub caddyfile: String,
    pub systemd_units: Vec<SystemdUnit>,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct SystemdUnit {
    pub name: String,
    pub content: String,
}

#[derive(Clone, Debug, Eq, PartialEq)]
pub struct RenderedPaths {
    pub caddyfile: PathBuf,
    pub systemd_dir: PathBuf,
}

pub fn render_artifacts(map: &ServiceMap) -> RenderedArtifacts {
    let mut systemd_units = map
        .deno_services()
        .map(|service| render_systemd_unit(map, service))
        .collect::<Vec<_>>();

    if let Some(pocketbase) = &map.pocketbase {
        systemd_units.push(render_pocketbase_systemd_unit(pocketbase));
    }

    systemd_units.sort_by(|left, right| left.name.cmp(&right.name));

    RenderedArtifacts {
        caddyfile: render_caddyfile(map),
        systemd_units,
    }
}

pub fn write_artifacts(map: &ServiceMap, output_dir: &Path) -> Result<RenderedPaths> {
    let artifacts = render_artifacts(map);
    let systemd_dir = output_dir.join("systemd");

    fs::create_dir_all(&systemd_dir)
        .with_context(|| format!("failed to create `{}`", systemd_dir.display()))?;

    let caddyfile = output_dir.join("Caddyfile");
    fs::write(&caddyfile, artifacts.caddyfile)
        .with_context(|| format!("failed to write `{}`", caddyfile.display()))?;

    for unit in artifacts.systemd_units {
        let path = systemd_dir.join(&unit.name);
        fs::write(&path, unit.content)
            .with_context(|| format!("failed to write `{}`", path.display()))?;
    }

    Ok(RenderedPaths {
        caddyfile,
        systemd_dir,
    })
}

fn render_caddyfile(map: &ServiceMap) -> String {
    let mut by_host: BTreeMap<String, Vec<&ResolvedService>> = BTreeMap::new();

    for service in &map.services {
        by_host
            .entry(service.host.clone())
            .or_default()
            .push(service);
    }

    let mut output = String::new();
    output.push_str("# Generated by vaieart-services. Do not edit this managed file by hand.\n\n");

    for (host, mut services) in by_host {
        services.sort_by(compare_routes);

        output.push_str(&host);
        output.push_str(" {\n");

        for service in &services {
            if service.route_path != "/" {
                output.push_str("    redir ");
                output.push_str(&service.route_path);
                output.push(' ');
                output.push_str(&service.route_path);
                output.push_str("/ permanent\n");
            }
        }

        for service in services {
            match &service.kind {
                ResolvedServiceKind::StaticSite => {
                    render_static_route(&mut output, service);
                }
                ResolvedServiceKind::DenoApp { port, .. } => {
                    render_deno_route(&mut output, service, *port);
                }
            }
        }

        output.push_str("}\n\n");
    }

    if let Some(pocketbase) = &map.pocketbase {
        render_pocketbase_caddy_block(&mut output, pocketbase);
    }

    if let Some(host) = &map.caddy.www_redirect_host {
        output.push_str(host);
        output.push_str(" {\n");
        output.push_str("    redir https://");
        output.push_str(&map.caddy.primary_host);
        output.push_str("{uri} permanent\n");
        output.push_str("}\n");
    }

    output
}

fn render_static_route(output: &mut String, service: &ResolvedService) {
    if service.route_path == "/" {
        output.push_str("    handle {\n");
    } else {
        output.push_str("    handle_path ");
        output.push_str(&service.route_path);
        output.push_str("/* {\n");
    }

    output.push_str("        root * ");
    output.push_str(&service.remote_path);
    output.push('\n');
    output.push_str("        try_files {path} {path}/ /index.html\n");
    output.push_str("        file_server\n");
    output.push_str("    }\n");
}

fn render_deno_route(output: &mut String, service: &ResolvedService, port: u16) {
    if service.route_path == "/" {
        output.push_str("    handle {\n");
    } else {
        output.push_str("    handle ");
        output.push_str(&service.route_path);
        output.push_str("/* {\n");
    }

    output.push_str("        reverse_proxy 127.0.0.1:");
    output.push_str(&port.to_string());
    output.push('\n');
    output.push_str("    }\n");
}

fn render_pocketbase_caddy_block(output: &mut String, pocketbase: &ResolvedPocketBase) {
    output.push_str(&pocketbase.host);
    output.push_str(" {\n");
    output.push_str("    request_body {\n");
    output.push_str("        max_size ");
    output.push_str(&pocketbase.request_body_max_size);
    output.push('\n');
    output.push_str("    }\n\n");
    output.push_str("    reverse_proxy 127.0.0.1:");
    output.push_str(&pocketbase.port.to_string());
    output.push_str(" {\n");
    output.push_str("        transport http {\n");
    output.push_str("            read_timeout ");
    output.push_str(&pocketbase.read_timeout);
    output.push('\n');
    output.push_str("        }\n");
    output.push_str("    }\n");
    output.push_str("}\n\n");
}

fn render_systemd_unit(map: &ServiceMap, service: &ResolvedService) -> SystemdUnit {
    let ResolvedServiceKind::DenoApp {
        port,
        entrypoint,
        service_name,
        environment,
    } = &service.kind
    else {
        unreachable!("systemd unit rendering only receives deno services");
    };

    let mut env = environment.clone();
    env.entry("HOST".to_string())
        .or_insert_with(|| "127.0.0.1".to_string());
    env.entry("PORT".to_string())
        .or_insert_with(|| port.to_string());

    let mut output = String::new();
    output.push_str("[Unit]\n");
    output.push_str("Description=vaie.art managed Deno service - ");
    output.push_str(&service.name);
    output.push('\n');
    output.push_str("After=network-online.target\n");
    output.push_str("Wants=network-online.target\n\n");
    output.push_str("[Service]\n");
    output.push_str("Type=simple\n");
    output.push_str("User=root\n");
    output.push_str("Group=root\n");
    output.push_str("WorkingDirectory=");
    output.push_str(&service.remote_path);
    output.push('\n');

    for (key, value) in env {
        output.push_str("Environment=");
        output.push_str(&systemd_environment_value(&key, &value));
        output.push('\n');
    }

    output.push_str("ExecStart=");
    output.push_str(&map.remote.deno_bin);
    output.push_str(" run -A ");
    output.push_str(&entrypoint_argument(entrypoint));
    output.push('\n');
    output.push_str("Restart=on-failure\n");
    output.push_str("RestartSec=3\n\n");
    output.push_str("[Install]\n");
    output.push_str("WantedBy=multi-user.target\n");

    SystemdUnit {
        name: service_name.clone(),
        content: output,
    }
}

fn render_pocketbase_systemd_unit(pocketbase: &ResolvedPocketBase) -> SystemdUnit {
    let mut output = String::new();
    output.push_str("[Unit]\n");
    output.push_str("Description=vaie.art managed PocketBase service - ");
    output.push_str(&pocketbase.name);
    output.push('\n');
    output.push_str("After=network-online.target\n");
    output.push_str("Wants=network-online.target\n\n");
    output.push_str("[Service]\n");
    output.push_str("Type=simple\n");
    output.push_str("User=root\n");
    output.push_str("Group=root\n");
    output.push_str("WorkingDirectory=");
    output.push_str(&pocketbase.remote_path);
    output.push('\n');
    output.push_str("LimitNOFILE=4096\n");

    if let Some(environment_file) = &pocketbase.environment_file {
        output.push_str("EnvironmentFile=");
        output.push_str(environment_file);
        output.push('\n');
    }

    output.push_str("ExecStart=");
    output.push_str(&pocketbase.binary);
    output.push_str(" serve --http=127.0.0.1:");
    output.push_str(&pocketbase.port.to_string());
    output.push_str(" --dir=");
    output.push_str(&pocketbase.data_dir);
    output.push_str(" --migrationsDir=");
    output.push_str(&remote_child(&pocketbase.remote_path, "pb_migrations"));

    if let Some(encryption_env) = &pocketbase.encryption_env {
        output.push_str(" --encryptionEnv=");
        output.push_str(encryption_env);
    }

    output.push('\n');
    output.push_str("Restart=on-failure\n");
    output.push_str("RestartSec=3\n\n");
    output.push_str("[Install]\n");
    output.push_str("WantedBy=multi-user.target\n");

    SystemdUnit {
        name: pocketbase.service_name.clone(),
        content: output,
    }
}

fn compare_routes(left: &&ResolvedService, right: &&ResolvedService) -> Ordering {
    match (left.route_path == "/", right.route_path == "/") {
        (true, false) => Ordering::Greater,
        (false, true) => Ordering::Less,
        _ => right
            .route_path
            .len()
            .cmp(&left.route_path.len())
            .then_with(|| left.route_path.cmp(&right.route_path)),
    }
}

fn remote_child(parent: &str, child: &str) -> String {
    format!(
        "{}/{}",
        parent.trim_end_matches('/'),
        child.trim_start_matches('/'),
    )
}

fn entrypoint_argument(entrypoint: &str) -> String {
    if entrypoint.starts_with('/') || entrypoint.starts_with("./") {
        entrypoint.to_string()
    } else {
        format!("./{entrypoint}")
    }
}

fn systemd_environment_value(key: &str, value: &str) -> String {
    format!(
        "\"{}={}\"",
        key,
        value.replace('\\', "\\\\").replace('"', "\\\"")
    )
}

#[cfg(test)]
mod tests {
    use super::{super::config::Config, *};
    use std::fs;
    use tempfile::TempDir;

    #[test]
    fn renders_current_vaie_and_pudle_caddyfile() {
        let map = fixture_map();
        let artifacts = render_artifacts(&map);

        assert_eq!(
            artifacts.caddyfile,
            r#"# Generated by vaieart-services. Do not edit this managed file by hand.

vaie.art {
    redir /pudle /pudle/ permanent
    handle_path /pudle/* {
        root * /web/pudle
        try_files {path} {path}/ /index.html
        file_server
    }
    handle {
        reverse_proxy 127.0.0.1:3000
    }
}

www.vaie.art {
    redir https://vaie.art{uri} permanent
}
"#,
        );
    }

    #[test]
    fn renders_subpath_deno_route_without_stripping_prefix() {
        let dir = TempDir::new().expect("temp dir");
        fs::create_dir_all(dir.path().join("src/submodules/plover-hatchery/web"))
            .expect("hatchery web dir");
        let config_path = dir.path().join("services.toml");
        fs::write(
            &config_path,
            r#"
manifest_version = 1

[remote]
host = "vaie.art"
user = "root"

[caddy]
primary_host = "vaie.art"

[[services]]
name = "hatchery-web"
kind = "deno_app"
local_path = "src/submodules/plover-hatchery/web"
remote_path = "/srv/hatchery"
port = 3001
entrypoint = "index.js"
route_path = "/hatchery"
"#,
        )
        .expect("write config");

        let map = Config::load(&config_path)
            .expect("load config")
            .validate(&config_path)
            .expect("validate config");
        let artifacts = render_artifacts(&map);

        assert_eq!(
            artifacts.caddyfile,
            r#"# Generated by vaieart-services. Do not edit this managed file by hand.

vaie.art {
    redir /hatchery /hatchery/ permanent
    handle /hatchery/* {
        reverse_proxy 127.0.0.1:3001
    }
}

"#,
        );
    }

    #[test]
    fn renders_pocketbase_caddy_and_systemd_unit() {
        let dir = TempDir::new().expect("temp dir");
        fs::create_dir_all(dir.path().join("src/pocketbase/pb_migrations")).expect("pb dir");
        fs::create_dir_all(dir.path().join("src/submodules/pudle")).expect("pudle dir");
        let config_path = dir.path().join("services.toml");
        fs::write(
            &config_path,
            r#"
manifest_version = 1

[remote]
host = "vaie.art"
user = "root"

[caddy]
primary_host = "vaie.art"

[pocketbase]
name = "site-pocketbase"
host = "pb.vaie.art"
source_path = "src/pocketbase"
remote_path = "/srv/vaieart-pocketbase"
data_dir = "/var/lib/vaieart-pocketbase/pb_data"
backup_dir = "/var/backups/vaieart-pocketbase"
port = 8090
environment_file = "/etc/vaieart/pocketbase.env"
encryption_env = "PB_ENCRYPTION_KEY"

[[services]]
name = "pudle"
kind = "static_site"
local_path = "src/submodules/pudle"
remote_path = "/web/pudle"
route_path = "/pudle"
"#,
        )
        .expect("write config");

        let map = Config::load(&config_path)
            .expect("load config")
            .validate(&config_path)
            .expect("validate config");
        let artifacts = render_artifacts(&map);

        assert!(artifacts.caddyfile.contains("pb.vaie.art {"));
        assert!(artifacts.caddyfile.contains("max_size 25MB"));
        assert!(artifacts.caddyfile.contains("reverse_proxy 127.0.0.1:8090"));
        assert_eq!(artifacts.systemd_units.len(), 1);
        assert_eq!(
            artifacts.systemd_units[0].name,
            "vaieart-site-pocketbase.service",
        );
        assert!(
            artifacts.systemd_units[0]
                .content
                .contains("WorkingDirectory=/srv/vaieart-pocketbase")
        );
        assert!(
            artifacts.systemd_units[0]
                .content
                .contains("EnvironmentFile=/etc/vaieart/pocketbase.env")
        );
        assert!(artifacts.systemd_units[0].content.contains(
            "ExecStart=/usr/local/bin/pocketbase serve --http=127.0.0.1:8090 --dir=/var/lib/vaieart-pocketbase/pb_data --migrationsDir=/srv/vaieart-pocketbase/pb_migrations --encryptionEnv=PB_ENCRYPTION_KEY",
        ));
    }
    #[test]
    fn renders_current_systemd_unit() {
        let map = fixture_map();
        let artifacts = render_artifacts(&map);

        assert_eq!(artifacts.systemd_units.len(), 1);
        assert_eq!(artifacts.systemd_units[0].name, "vaieart-vaie-art.service");
        assert_eq!(
            artifacts.systemd_units[0].content,
            r#"[Unit]
Description=vaie.art managed Deno service - vaie.art
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=root
Group=root
WorkingDirectory=/srv/vaie.art
Environment="HOST=127.0.0.1"
Environment="PORT=3000"
ExecStart=/root/.deno/bin/deno run -A ./index.js
Restart=on-failure
RestartSec=3

[Install]
WantedBy=multi-user.target
"#,
        );
    }

    fn fixture_map() -> ServiceMap {
        let dir = TempDir::new().expect("temp dir");
        fs::create_dir_all(dir.path().join("src/submodules/vaie.art")).expect("vaie dir");
        fs::create_dir_all(dir.path().join("src/submodules/pudle")).expect("pudle dir");
        let config_path = dir.path().join("services.toml");
        fs::write(
            &config_path,
            r#"
manifest_version = 1

[remote]
host = "vaie.art"
user = "root"

[caddy]
primary_host = "vaie.art"
www_redirect_host = "www.vaie.art"

[[services]]
name = "vaie.art"
kind = "deno_app"
local_path = "src/submodules/vaie.art"
remote_path = "/srv/vaie.art"
port = 3000
entrypoint = "index.js"

[[services]]
name = "pudle"
kind = "static_site"
local_path = "src/submodules/pudle"
remote_path = "/web/pudle"
route_path = "/pudle"
"#,
        )
        .expect("write config");

        Config::load(&config_path)
            .expect("load config")
            .validate(&config_path)
            .expect("validate config")
    }
}
