use std::cmp::Ordering;
use std::collections::BTreeMap;

use super::super::config::{ResolvedPocketBase, ResolvedService, ResolvedServiceKind, ServiceMap};

pub(super) fn render_caddyfile(map: &ServiceMap) -> String {
    let mut by_host: BTreeMap<String, Vec<&ResolvedService>> = BTreeMap::new();

    for service in &map.services {
        by_host
            .entry(service.host.clone())
            .or_default()
            .push(service);
    }

    let mut output = String::new();
    output.push_str("# Generated by vaieart-services. Do not edit this managed file by hand.\n\n");

    for (host, mut services) in by_host {
        services.sort_by(compare_routes);

        output.push_str(&host);
        output.push_str(" {\n");

        for service in &services {
            if service.route_path != "/" {
                output.push_str("    redir ");
                output.push_str(&service.route_path);
                output.push(' ');
                output.push_str(&service.route_path);
                output.push_str("/ permanent\n");
            }
        }

        for service in services {
            match &service.kind {
                ResolvedServiceKind::StaticSite => {
                    render_static_route(&mut output, service);
                }
                ResolvedServiceKind::DenoApp { port, .. } => {
                    render_deno_route(&mut output, service, *port);
                }
            }
        }

        output.push_str("}\n\n");
    }

    if let Some(pocketbase) = &map.pocketbase {
        render_pocketbase_caddy_block(&mut output, pocketbase);
    }

    if let Some(host) = &map.caddy.www_redirect_host {
        output.push_str(host);
        output.push_str(" {\n");
        output.push_str("    redir https://");
        output.push_str(&map.caddy.primary_host);
        output.push_str("{uri} permanent\n");
        output.push_str("}\n");
    }

    output
}

fn render_static_route(output: &mut String, service: &ResolvedService) {
    if service.route_path == "/" {
        output.push_str("    handle {\n");
    } else {
        output.push_str("    handle_path ");
        output.push_str(&service.route_path);
        output.push_str("/* {\n");
    }

    output.push_str("        root * ");
    output.push_str(&service.remote_path);
    output.push('\n');
    output.push_str("        try_files {path} {path}/ /index.html\n");
    output.push_str("        file_server\n");
    output.push_str("    }\n");
}

fn render_deno_route(output: &mut String, service: &ResolvedService, port: u16) {
    if service.route_path == "/" {
        output.push_str("    handle {\n");
    } else {
        output.push_str("    handle ");
        output.push_str(&service.route_path);
        output.push_str("/* {\n");
    }

    output.push_str("        reverse_proxy 127.0.0.1:");
    output.push_str(&port.to_string());
    output.push('\n');
    output.push_str("    }\n");
}

fn render_pocketbase_caddy_block(output: &mut String, pocketbase: &ResolvedPocketBase) {
    output.push_str(&pocketbase.host);
    output.push_str(" {\n");
    output.push_str("    request_body {\n");
    output.push_str("        max_size ");
    output.push_str(&pocketbase.request_body_max_size);
    output.push('\n');
    output.push_str("    }\n\n");
    output.push_str("    reverse_proxy 127.0.0.1:");
    output.push_str(&pocketbase.port.to_string());
    output.push_str(" {\n");
    output.push_str("        transport http {\n");
    output.push_str("            read_timeout ");
    output.push_str(&pocketbase.read_timeout);
    output.push('\n');
    output.push_str("        }\n");
    output.push_str("    }\n");
    output.push_str("}\n\n");
}

fn compare_routes(left: &&ResolvedService, right: &&ResolvedService) -> Ordering {
    match (left.route_path == "/", right.route_path == "/") {
        (true, false) => Ordering::Greater,
        (false, true) => Ordering::Less,
        _ => right
            .route_path
            .len()
            .cmp(&left.route_path.len())
            .then_with(|| left.route_path.cmp(&right.route_path)),
    }
}
