use super::{super::config::Config, *};
use std::fs;
use tempfile::TempDir;

#[test]
fn renders_current_vaie_and_pudle_caddyfile() {
    let map = fixture_map();
    let artifacts = render_artifacts(&map);

    assert_eq!(
        artifacts.caddyfile,
        r#"# Generated by vaieart-services. Do not edit this managed file by hand.

vaie.art {
    redir /pudle /pudle/ permanent
    handle_path /pudle/* {
        root * /web/pudle
        try_files {path} {path}/ /index.html
        file_server
    }
    handle {
        reverse_proxy 127.0.0.1:3000
    }
}

www.vaie.art {
    redir https://vaie.art{uri} permanent
}
"#,
    );
}

#[test]
fn renders_subpath_deno_route_without_stripping_prefix() {
    let dir = TempDir::new().expect("temp dir");
    fs::create_dir_all(dir.path().join("src/submodules/plover-hatchery/web"))
        .expect("hatchery web dir");
    let config_path = dir.path().join("services.toml");
    fs::write(
        &config_path,
        r#"
manifest_version = 1

[remote]
host = "vaie.art"
user = "root"

[caddy]
primary_host = "vaie.art"

[[services]]
name = "hatchery-web"
kind = "deno_app"
local_path = "src/submodules/plover-hatchery/web"
remote_path = "/srv/hatchery"
port = 3001
entrypoint = "index.js"
route_path = "/hatchery"
"#,
    )
    .expect("write config");

    let map = Config::load(&config_path)
        .expect("load config")
        .validate(&config_path)
        .expect("validate config");
    let artifacts = render_artifacts(&map);

    assert_eq!(
        artifacts.caddyfile,
        r#"# Generated by vaieart-services. Do not edit this managed file by hand.

vaie.art {
    redir /hatchery /hatchery/ permanent
    handle /hatchery/* {
        reverse_proxy 127.0.0.1:3001
    }
}

"#,
    );
}

#[test]
fn renders_pocketbase_caddy_and_systemd_unit() {
    let dir = TempDir::new().expect("temp dir");
    fs::create_dir_all(dir.path().join("src/pocketbase/pb_migrations")).expect("pb dir");
    fs::create_dir_all(dir.path().join("src/submodules/pudle")).expect("pudle dir");
    let config_path = dir.path().join("services.toml");
    fs::write(
        &config_path,
        r#"
manifest_version = 1

[remote]
host = "vaie.art"
user = "root"

[caddy]
primary_host = "vaie.art"

[pocketbase]
name = "site-pocketbase"
host = "pb.vaie.art"
source_path = "src/pocketbase"
remote_path = "/srv/vaieart-pocketbase"
data_dir = "/var/lib/vaieart-pocketbase/pb_data"
backup_dir = "/var/backups/vaieart-pocketbase"
port = 8090
environment_file = "/etc/vaieart/pocketbase.env"
encryption_env = "PB_ENCRYPTION_KEY"

[pocketbase.warp_proxy]
port = 40000

[[services]]
name = "pudle"
kind = "static_site"
local_path = "src/submodules/pudle"
remote_path = "/web/pudle"
route_path = "/pudle"
"#,
    )
    .expect("write config");

    let map = Config::load(&config_path)
        .expect("load config")
        .validate(&config_path)
        .expect("validate config");
    let artifacts = render_artifacts(&map);

    assert!(artifacts.caddyfile.contains("pb.vaie.art {"));
    assert!(artifacts.caddyfile.contains("max_size 25MB"));
    assert!(artifacts.caddyfile.contains("reverse_proxy 127.0.0.1:8090"));
    assert_eq!(artifacts.systemd_units.len(), 2);
    let pocketbase_unit = artifacts
        .systemd_units
        .iter()
        .find(|unit| unit.name == "vaieart-site-pocketbase.service")
        .expect("PocketBase unit");
    let warp_proxy_unit = artifacts
        .systemd_units
        .iter()
        .find(|unit| unit.name == "vaieart-site-pocketbase-warp-proxy.service")
        .expect("WARP proxy unit");

    assert_eq!(
        warp_proxy_unit.content,
        r#"[Unit]
Description=vaie.art managed WARP proxy for PocketBase - site-pocketbase
After=network-online.target warp-svc.service
Wants=network-online.target
Requires=warp-svc.service
Before=vaieart-site-pocketbase.service

[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/bin/warp-cli tunnel protocol set MASQUE
ExecStart=/usr/bin/warp-cli mode proxy
ExecStart=/usr/bin/warp-cli proxy port 40000
ExecStart=/usr/bin/warp-cli connect
ExecStart=/usr/bin/curl --fail --silent --show-error --retry 10 --retry-all-errors --retry-delay 1 --retry-max-time 60 --connect-timeout 3 --max-time 8 --proxy http://127.0.0.1:40000 https://discord.com/api/v10/gateway
TimeoutStartSec=120

[Install]
WantedBy=multi-user.target
"#,
    );
    assert!(
        pocketbase_unit
            .content
            .contains("After=network-online.target vaieart-site-pocketbase-warp-proxy.service")
    );
    assert!(
        pocketbase_unit
            .content
            .contains("Requires=vaieart-site-pocketbase-warp-proxy.service")
    );
    assert!(
        pocketbase_unit
            .content
            .contains("WorkingDirectory=/srv/vaieart-pocketbase")
    );
    assert!(
        pocketbase_unit
            .content
            .contains("EnvironmentFile=/etc/vaieart/pocketbase.env")
    );
    assert!(
        pocketbase_unit
            .content
            .contains("Environment=\"HTTPS_PROXY=http://127.0.0.1:40000\"")
    );
    assert!(
        pocketbase_unit
            .content
            .contains("Environment=\"NO_PROXY=127.0.0.1,localhost,::1\"")
    );
    assert!(pocketbase_unit.content.contains(
            "ExecStart=/usr/local/bin/pocketbase serve --http=127.0.0.1:8090 --dir=/var/lib/vaieart-pocketbase/pb_data --migrationsDir=/srv/vaieart-pocketbase/pb_migrations --encryptionEnv=PB_ENCRYPTION_KEY",
        ));
}
#[test]
fn renders_current_systemd_unit() {
    let map = fixture_map();
    let artifacts = render_artifacts(&map);

    assert_eq!(artifacts.systemd_units.len(), 1);
    assert_eq!(artifacts.systemd_units[0].name, "vaieart-vaie-art.service");
    assert_eq!(
        artifacts.systemd_units[0].content,
        r#"[Unit]
Description=vaie.art managed Deno service - vaie.art
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=root
Group=root
WorkingDirectory=/srv/vaie.art
Environment="HOST=127.0.0.1"
Environment="PORT=3000"
ExecStart=/root/.deno/bin/deno run -A ./index.js
Restart=on-failure
RestartSec=3

[Install]
WantedBy=multi-user.target
"#,
    );
}

fn fixture_map() -> ServiceMap {
    let dir = TempDir::new().expect("temp dir");
    fs::create_dir_all(dir.path().join("src/submodules/vaie.art")).expect("vaie dir");
    fs::create_dir_all(dir.path().join("src/submodules/pudle")).expect("pudle dir");
    let config_path = dir.path().join("services.toml");
    fs::write(
        &config_path,
        r#"
manifest_version = 1

[remote]
host = "vaie.art"
user = "root"

[caddy]
primary_host = "vaie.art"
www_redirect_host = "www.vaie.art"

[[services]]
name = "vaie.art"
kind = "deno_app"
local_path = "src/submodules/vaie.art"
remote_path = "/srv/vaie.art"
port = 3000
entrypoint = "index.js"

[[services]]
name = "pudle"
kind = "static_site"
local_path = "src/submodules/pudle"
remote_path = "/web/pudle"
route_path = "/pudle"
"#,
    )
    .expect("write config");

    Config::load(&config_path)
        .expect("load config")
        .validate(&config_path)
        .expect("validate config")
}
